SELECT FLAVOR
FROM (
    SELECT F.FLAVOR,
    (F.TOTAL_ORDER + july.TOTAL_ORDER) AS TOTAL_ORDER
     FROM FIRST_HALF F
    INNER JOIN (
     SELECT FLAVOR, 
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) july
    ON
      F.FLAVOR = july.FLAVOR
    ) combined
     ORDER BY TOTAL_ORDER DESC
     LIMIT 3;